#!/bin/sh

if type -t autoreconf >/dev/null
then
    autoreconf -v
else
    set -e
    set -x

    aclocal -I config
    libtoolize --force
    autoheader
    automake --gnu --add-missing
    autoconf
fi
